### ISSUE TITLE
Assumption Input tab (Kenya) Navigation Link issues

### ISSUE THREAD

**Issue by imujawar** [achafetz/DataPack#78] opened 2017-12-19 18:54 UTC
PVLS is missing in the Navigation link and the order is off. The references are also misaligned. 

![image](https://user-images.githubusercontent.com/18144056/34173594-f80ac01e-e4c3-11e7-8980-39a6c52400d8.png)

@achafetz

**Comment by achafetz** [comment] 2017-12-19 19:02
Duplicate of #25

**Closed as completed by achafetz** 2017-12-19 19:02 UTC
