### ISSUE TITLE
Schlenker: Uganda Datapack DATIM Indicator Table with incorrect values for HTS_TST_POS and YIELD

### ISSUE THREAD

**Issue by annakradin** [achafetz/DataPack#157] opened 2018-02-15 02:19 UTC
From Kristy Schlenker: I noticed that in the DATIM Indicator Table tab the FY17 HTS_TST_POS <15 value is actually pulling in the POS 15+ value (see attached screenshot). As a result, the FY17 HTS_TST <15 Yield column is also incorrect (showing peds yields of over 100% in some cases). I looked back at old versions of our datapack from last week & it looks like an incorrect value has always been there.
 
Do these columns impact any calculations elsewhere in the datpack, or is this just one of those places where historical data is shown for context but not used in any calculations? I'm trying to figure out if we need to fix it or not. I think it is just there for context, but I want to confirm.

**Comment by achafetz** [comment] 2018-02-15 16:44
Duplicate of #153

**Closed as completed by achafetz** 2018-02-15 16:44 UTC
