### ISSUE TITLE
Formatting Issue: Targeting Calculation Tab 

### ISSUE THREAD

**Issue by Bddamulira** [achafetz/DataPack#107] opened 2017-12-19 20:26 UTC
Column CR 
FY19 TX_RET <15 displaying as a decimal 

--

**Comment by achafetz** [comment] 2017-12-19 21:15
Duplicate of #109

**Closed as completed by achafetz** 2017-12-19 21:15 UTC

**Comment by KTmonkey** [comment] 2017-12-21 13:13
Hey, 

Target Calculation tab, Cols L, P, and BB all have decimal places.

**Comment by achafetz** [comment] 2017-12-21 13:56
all intentional. just don't want decimals with non-percentages
